# Generated by Django 5.1.1 on 2024-10-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAcercamientos', '0002_alter_acercamientocooperacion_reporte'),
        ('reporteAportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyoherramientas',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteAcercamientos.reporte', verbose_name='Reporte'),
        ),
    ]
