# Generated by Django 5.1.1 on 2024-10-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyoviajes',
            name='resaltado_apoyo',
            field=models.TextField(max_length=255, verbose_name='¿Qué resaltaría de este apoyo?'),
        ),
    ]
