# Generated by Django 5.1.1 on 2024-09-25 15:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAportes', '0002_remove_apoyoterritorios_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Área Profesional')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Tipo de Personal')),
            ],
        ),
        migrations.CreateModel(
            name='ApoyoContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_personas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Cantidad de personas')),
                ('tiempo_servicio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Tiempo de servicio en meses')),
                ('otro_tipo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro, ¿Cúales?')),
                ('objetivo_contratos', models.TextField(max_length=255, verbose_name='¿Cuál es el objetivo principal de los contratos del personal con el cual apoya este proyecto / cooperante?')),
                ('resaltar_apoyo', models.TextField(max_length=255, verbose_name='¿Qué resaltaría de este apoyo relacionado con la contratación de personal por parte de este cooperante?')),
                ('area_profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporteAportes.areaprofesional')),
                ('tipo_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteAportes.tipopersonal')),
            ],
            options={
                'verbose_name': 'Apoyo de Contratación',
                'verbose_name_plural': 'Apoyo de Contratación',
            },
        ),
    ]
