# Generated by Django 5.1.1 on 2024-10-02 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAportes', '0002_alter_apoyoviajes_resaltado_apoyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrataciondetalle',
            name='area_profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporteAportes.areaprofesional'),
        ),
    ]
