# Generated by Django 5.1.1 on 2024-10-03 22:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAportes', '0003_alter_contrataciondetalle_area_profesional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoyomaterial',
            name='cantidad_originales',
        ),
        migrations.RemoveField(
            model_name='apoyomaterial',
            name='cantidad_reproducciones',
        ),
        migrations.RemoveField(
            model_name='apoyomaterial',
            name='objetivo_principal',
        ),
        migrations.RemoveField(
            model_name='apoyomaterial',
            name='publico_destinatario',
        ),
        migrations.RemoveField(
            model_name='apoyomaterial',
            name='tipo_material',
        ),
        migrations.RemoveField(
            model_name='apoyomaterial',
            name='titulo_material',
        ),
        migrations.CreateModel(
            name='ApoyoMaterialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_material', models.CharField(max_length=255, verbose_name='Título material')),
                ('objetivo_principal', models.TextField(verbose_name='Objetivo principal')),
                ('publico_destinatario', models.CharField(max_length=255, verbose_name='Público destinatario')),
                ('cantidad_originales', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Cantidad originales')),
                ('cantidad_reproducciones', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Cantidad reproducciones')),
                ('apoyo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteAportes.apoyomaterial')),
                ('tipo_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporteAportes.tipomaterial')),
            ],
        ),
    ]
