# Generated by Django 5.1.1 on 2024-09-25 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAcercamientos', '0001_initial'),
        ('reporteAportes', '0003_areaprofesional_tipopersonal_apoyocontratacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Tipo de Material')),
            ],
        ),
        migrations.CreateModel(
            name='ApoyoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_material', models.CharField(max_length=255, verbose_name='Título material')),
                ('objetivo_principal', models.TextField(verbose_name='Objetivo principal')),
                ('publico_destinatario', models.CharField(max_length=255, verbose_name='Público destinatario')),
                ('cantidad_originales', models.PositiveIntegerField(verbose_name='Cantidad originales')),
                ('cantidad_reproducciones', models.PositiveIntegerField(verbose_name='Cantidad reproducciones')),
                ('resaltar_apoyo', models.TextField(max_length=255, verbose_name='Que resaltaría de este apoyo a través de la producción de materiales')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteAcercamientos.reporte')),
                ('tipo_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporteAportes.tipomaterial')),
            ],
            options={
                'verbose_name': 'Apoyo en Producción de Materiales',
                'verbose_name_plural': 'Apoyo en Producción de Materiales',
            },
        ),
    ]
