# Generated by Django 5.1.1 on 2024-10-03 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAportes', '0004_remove_apoyomaterial_cantidad_originales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='publicoDestinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del público objetivo')),
            ],
        ),
        migrations.AlterField(
            model_name='apoyomaterialdetalle',
            name='publico_destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporteAportes.publicodestinatario'),
        ),
    ]
