# Generated by Django 5.1.1 on 2024-09-25 17:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAportes', '0004_tipomaterial_apoyomaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Tipo de Herramienta / Equipo')),
            ],
        ),
        migrations.RemoveField(
            model_name='apoyoeventos',
            name='reporte',
        ),
        migrations.RemoveField(
            model_name='apoyomaterial',
            name='reporte',
        ),
        migrations.RemoveField(
            model_name='apoyoviajes',
            name='reporte',
        ),
        migrations.CreateModel(
            name='ApoyoHerramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Cantidad recibida')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('observaciones', models.CharField(max_length=255, verbose_name='Observaciones / detalle')),
                ('tipo_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteAportes.tipoherramienta')),
            ],
            options={
                'verbose_name': 'Apoyo de Herramientas',
                'verbose_name_plural': 'Apoyo de Herramientas',
            },
        ),
    ]
