# Generated by Django 5.1.1 on 2024-10-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAportes', '0005_publicodestinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyoherramientas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='apoyoherramientas',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones / detalle'),
        ),
    ]
