# Generated by Django 5.1.1 on 2024-09-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAportes', '0006_tipocaso_apoyolitigio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Tipo de Apoyo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Tipo de Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ApoyoSeguridadAlimentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_proyectos', models.PositiveIntegerField(verbose_name='Cantidad proyectos')),
                ('cantidad_familias', models.PositiveIntegerField(verbose_name='Cantidad familias beneficiarias')),
                ('otro_apoyo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cual')),
                ('resaltar_apoyo', models.TextField(max_length=255, verbose_name='¿Qué resaltaría de este apoyo relacionado con seguridad alimentaria o proyectos productivos por parte de este proyecto / cooperante?')),
                ('tipo_apoyo', models.ManyToManyField(to='reporteAportes.tipoapoyo', verbose_name='Tipo de apoyo')),
                ('tipo_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteAportes.tipoproyecto')),
            ],
            options={
                'verbose_name': 'Apoyo a Seguridad Alimentaria',
                'verbose_name_plural': 'Apoyo a Seguridad Alimentaria',
            },
        ),
    ]
