# Generated by Django 5.1.1 on 2024-09-25 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAportes', '0007_tipoapoyo_tipoproyecto_apoyoseguridadalimentaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Acción')),
            ],
        ),
        migrations.CreateModel(
            name='ApoyoOrdenesJudiciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_apoyo', models.TextField(max_length=255, verbose_name='Indique el tipo de apoyo que ha recibido de este proyecto / cooperante para el cumplimiento de órdenes judiciales')),
                ('tipo_ordenes', models.TextField(max_length=255, verbose_name='¿Para qué tipo de órdenes judiciales recibió el apoyo?')),
                ('cantidad_sentencias', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Indique, si es posible, para cuántas sentencias ha contribuido el apoyo recibido de este proyecto / cooperante:')),
                ('cantidad_ordenes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Indique, si es posible, para cuántas órdenes ha contribuido el apoyo recibido de este proyecto / cooperante:')),
            ],
            options={
                'verbose_name': 'Apoyo para el Cumplimiento de Órdenes Judiciales',
                'verbose_name_plural': 'Apoyo para el Cumplimiento de Órdenes Judiciales',
            },
        ),
        migrations.CreateModel(
            name='ApoyoArchivoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuales_acciones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cuales')),
                ('comentarios', models.TextField(max_length=255, verbose_name='¿Qué resaltaría o que comentarios tiene sobre el apoyo recibido para la gestión documental?')),
                ('acciones', models.ManyToManyField(to='reporteAportes.accionarchivo', verbose_name='Indique el tipo de acciones para las cuales ha recibido apoyo')),
            ],
            options={
                'verbose_name': 'Apoyo en Gestión del Archivo Histórico',
                'verbose_name_plural': 'Apoyo en Gestión del Archivo Histórico',
            },
        ),
    ]
