# Generated by Django 5.1.1 on 2024-10-07 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioCooperacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocooperacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener entre 9 y 15 dígitos. Puede incluir el signo '+' al principio.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
