# Generated by Django 5.1.1 on 2024-09-22 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporteAcercamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCooperante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cooperante', models.CharField(max_length=255, verbose_name='Nombre del cooperante')),
                ('cual_cooperante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cual (cooperante)')),
                ('identificacion', models.CharField(max_length=50, verbose_name='Identificación')),
                ('nombre_implementador', models.CharField(default='Automático', max_length=255, verbose_name='Nombre del implementador u operador')),
                ('programa_proyecto_plan', models.CharField(max_length=255, verbose_name='Programa/proyecto o plan')),
                ('cual_programa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cual (programa/proyecto o plan)')),
                ('linea_accion', models.CharField(max_length=255, verbose_name='Línea de acción/componente')),
                ('cual_linea_accion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cual (línea de acción)')),
                ('rol_quien_reporta', models.CharField(max_length=255, verbose_name='Rol de quien reporta')),
                ('cual_rol_reporta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cual (rol quien reporta)')),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reporteAcercamientos.reporte')),
            ],
            options={
                'db_table': 'datos_cooperante',
            },
        ),
        migrations.CreateModel(
            name='LogrosAvances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_1', models.CharField(default='Automático', max_length=255, verbose_name='Resultado 1')),
                ('logros_avances_1', models.CharField(max_length=50, verbose_name='Logros y/o avances 1')),
                ('departamento_1', models.CharField(max_length=255, verbose_name='Departamento 1')),
                ('municipio_1', models.CharField(max_length=255, verbose_name='Municipio 1')),
                ('adjunto_1', models.FileField(upload_to='adjuntos/', verbose_name='Adjunto 1')),
                ('resultado_2', models.CharField(default='Automático', max_length=255, verbose_name='Resultado 2')),
                ('logros_avances_2', models.CharField(blank=True, max_length=50, verbose_name='Logros y/o avances 2')),
                ('departamento_2', models.CharField(max_length=255, verbose_name='Departamento 2')),
                ('municipio_2', models.CharField(max_length=255, verbose_name='Municipio 2')),
                ('adjunto_2', models.FileField(upload_to='adjuntos/', verbose_name='Adjunto 2')),
                ('resultado_3', models.CharField(default='Automático', max_length=255, verbose_name='Resultado 3')),
                ('logros_avances_3', models.CharField(max_length=50, verbose_name='Logros y/o avances 3')),
                ('departamento_3', models.CharField(max_length=255, verbose_name='Departamento 3')),
                ('municipio_3', models.CharField(max_length=255, verbose_name='Municipio 3')),
                ('adjunto_3', models.FileField(upload_to='adjuntos/', verbose_name='Adjunto 3')),
                ('logros_significativos', models.CharField(max_length=50, verbose_name='Logros significativos en este periodo')),
                ('dificultades', models.CharField(max_length=50, verbose_name='Dificultades presentadas')),
                ('detalle_riesgo', models.CharField(blank=True, help_text="Solo si la respuesta es 'Sí'", max_length=50, null=True, verbose_name='Detalle situación de riesgo')),
                ('observaciones_generales', models.CharField(max_length=50, verbose_name='Observaciones o comentarios generales')),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reporteAcercamientos.reporte')),
            ],
            options={
                'db_table': 'logros_avances',
            },
        ),
    ]
