# Generated by Django 5.1.1 on 2024-09-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteProgramas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
