# Generated by Django 5.1.1 on 2024-09-23 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteProgramas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'db_table': 'resultado',
            },
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='adjunto_1',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='adjunto_2',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='adjunto_3',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='departamento_1',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='departamento_2',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='departamento_3',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='logros_avances_1',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='logros_avances_2',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='logros_avances_3',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='municipio_1',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='municipio_2',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='municipio_3',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='resultado_1',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='resultado_2',
        ),
        migrations.RemoveField(
            model_name='logrosavances',
            name='resultado_3',
        ),
        migrations.AlterField(
            model_name='logrosavances',
            name='detalle_riesgo',
            field=models.CharField(blank=True, help_text="Solo si la respuesta es 'Sí'", max_length=200, null=True, verbose_name='Detalle situación de riesgo'),
        ),
        migrations.AlterField(
            model_name='logrosavances',
            name='dificultades',
            field=models.CharField(max_length=200, verbose_name='Dificultades presentadas'),
        ),
        migrations.AlterField(
            model_name='logrosavances',
            name='logros_significativos',
            field=models.CharField(max_length=200, verbose_name='Logros significativos en este periodo'),
        ),
        migrations.AlterField(
            model_name='logrosavances',
            name='observaciones_generales',
            field=models.CharField(max_length=200, verbose_name='Observaciones o comentarios generales'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logros_avances_texto', models.CharField(max_length=200, verbose_name='Logros y/o avances')),
                ('adjunto', models.FileField(upload_to='adjuntos/', verbose_name='Adjunto')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.departamento')),
                ('logros_avances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='reporteProgramas.logrosavances')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.municipio')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.resultado')),
            ],
            options={
                'db_table': 'logro',
            },
        ),
    ]
