# Generated by Django 5.1.1 on 2024-10-04 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteProgramas', '0002_remove_datoscooperante_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscooperante',
            name='cooperante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.cooperante'),
        ),
        migrations.AlterField(
            model_name='datoscooperante',
            name='identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.acuerdo'),
        ),
        migrations.AlterField(
            model_name='datoscooperante',
            name='linea_accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.lineaaccion'),
        ),
        migrations.AlterField(
            model_name='datoscooperante',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.operador'),
        ),
        migrations.AlterField(
            model_name='datoscooperante',
            name='proyecto_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.proyectoplan'),
        ),
    ]
