# Generated by Django 5.1.1 on 2024-09-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteProgramas', '0002_alter_resultado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperante',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cooperante',
            name='nombre_corto',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cooperante',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='operador',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operador',
            name='nombre_corto',
            field=models.CharField(max_length=10),
        ),
    ]
