# Generated by Django 5.1.1 on 2024-09-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteProgramas', '0002_departamento_resultado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrosavances',
            name='riesgo_relacionamiento',
            field=models.BooleanField(default=False, verbose_name='¿Se presentó alguna situación de riesgo en el relacionamiento con el cooperante?'),
        ),
    ]
