# Generated by Django 5.1.1 on 2024-09-23 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteProgramas', '0003_logrosavances_riesgo_relacionamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('identificacion', models.CharField(max_length=100, unique=True)),
                ('pais', models.CharField(max_length=100)),
                ('tipo_cooperacion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('objetivo', models.TextField()),
            ],
            options={
                'db_table': 'acuerdo',
            },
        ),
        migrations.CreateModel(
            name='Cooperante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_corto', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'cooperante',
            },
        ),
        migrations.CreateModel(
            name='LineaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('responsable', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('nombre_supervisor', models.CharField(max_length=100)),
                ('formularios', models.TextField()),
                ('resultados', models.TextField()),
                ('observaciones', models.TextField()),
            ],
            options={
                'db_table': 'linea_accion',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_corto', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'operador',
            },
        ),
        migrations.CreateModel(
            name='ProyectoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cobertura_geografica', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('valor_aporte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_contrapartida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones_valor_economico', models.TextField()),
            ],
            options={
                'db_table': 'proyecto_plan',
            },
        ),
        migrations.CreateModel(
            name='AcuerdoCooperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.acuerdo')),
                ('cooperante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.cooperante')),
                ('lineas_accion', models.ManyToManyField(to='reporteProgramas.lineaaccion')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.operador')),
                ('proyecto_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteProgramas.proyectoplan')),
            ],
            options={
                'db_table': 'acuerdo_cooperacion',
            },
        ),
        migrations.DeleteModel(
            name='DatosCooperante',
        ),
    ]
