# Generated by Django 5.1.1 on 2024-09-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteProgramas', '0004_acuerdo_cooperante_lineaaccion_operador_proyectoplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCooperanteTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperante', models.CharField(max_length=100, unique=True)),
                ('identificacion', models.CharField(max_length=100, unique=True)),
                ('operador', models.CharField(max_length=100, unique=True)),
                ('proyecto_plan', models.CharField(max_length=100, unique=True)),
                ('linea_accion', models.CharField(max_length=100, unique=True)),
                ('rol', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'datos_cooperante_temporal',
            },
        ),
    ]
