# Generated by Django 5.1.1 on 2024-09-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAcercamientos', '0004_remove_reporte_unique_reporteacercamiento_per_user_periodo_and_more'),
        ('reporteProgramas', '0005_datoscooperantetemporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCooperante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperante', models.CharField(max_length=100, unique=True)),
                ('identificacion', models.CharField(max_length=100, unique=True)),
                ('operador', models.CharField(max_length=100, unique=True)),
                ('proyecto_plan', models.CharField(max_length=100, unique=True)),
                ('linea_accion', models.CharField(max_length=100, unique=True)),
                ('rol', models.CharField(max_length=100, unique=True)),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reporteAcercamientos.reporte')),
            ],
            options={
                'db_table': 'datos_cooperante',
            },
        ),
        migrations.DeleteModel(
            name='DatosCooperanteTemporal',
        ),
    ]
