# Generated by Django 5.1.1 on 2024-09-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteProgramas', '0006_datoscooperante_delete_datoscooperantetemporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscooperante',
            name='cooperante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datoscooperante',
            name='identificacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datoscooperante',
            name='linea_accion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datoscooperante',
            name='operador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datoscooperante',
            name='proyecto_plan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datoscooperante',
            name='rol',
            field=models.CharField(max_length=100),
        ),
    ]
