# Generated by Django 5.1.1 on 2024-09-22 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'db_table': 'dependencia',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='ReporteAcercamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_elaboracion', models.DateField()),
                ('periodo', models.IntegerField(choices=[(1, 'Periodo 1'), (2, 'Periodo 2'), (3, 'Periodo 3')])),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('estado', models.IntegerField(choices=[(0, 'Datos Quien Informa'), (1, 'Acercamiento de Cooperación'), (2, 'Necesidades de Cooperación'), (3, 'Finalizado')], default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporte_acercamiento',
            },
        ),
        migrations.CreateModel(
            name='NecesidadesCooperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necesidad_identificado', models.BooleanField(default=False)),
                ('necesidades_identificadas', models.TextField(blank=True, null=True)),
                ('cooperante_identificado', models.BooleanField(default=False)),
                ('cooperante', models.CharField(blank=True, max_length=100, null=True)),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reporteAcercamientos.reporteacercamiento')),
            ],
            options={
                'verbose_name': 'Necesidades de Cooperación',
                'verbose_name_plural': 'Necesidades de Cooperación',
                'db_table': 'necesidades_cooperacion',
            },
        ),
        migrations.CreateModel(
            name='AcercamientoCooperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(blank=True, max_length=200, null=True)),
                ('temas_perspectivas', models.TextField(blank=True, max_length=500, null=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteAcercamientos.reporteacercamiento')),
            ],
            options={
                'verbose_name': 'Acercamiento de Cooperación',
                'verbose_name_plural': 'Acercamientos de Cooperación',
                'db_table': 'acercamiento_cooperacion',
            },
        ),
        migrations.CreateModel(
            name='DatosQuienReporta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('correo_electronico_institucional', models.EmailField(blank=True, max_length=254, null=True)),
                ('dependencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporteAcercamientos.dependencia')),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reporteAcercamientos.reporteacercamiento')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporteAcercamientos.rol')),
            ],
            options={
                'verbose_name': 'Datos Quien Reporta',
                'verbose_name_plural': 'Datos Quien Reporta',
                'db_table': 'datos_quien_reporta',
            },
        ),
        migrations.AddConstraint(
            model_name='reporteacercamiento',
            constraint=models.UniqueConstraint(fields=('usuario', 'periodo'), name='unique_reporteAcercamiento_per_user_periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='reporteacercamiento',
            unique_together={('usuario', 'periodo')},
        ),
    ]
