# Generated by Django 5.1.1 on 2024-09-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAcercamientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acercamientocooperacion',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acercamientos', to='reporteAcercamientos.reporte'),
        ),
    ]
