# Generated by Django 5.1.1 on 2024-09-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAcercamientos', '0002_remove_reporte_unique_reporteacercamiento_per_user_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Reporte de Acercamiento'), (2, 'Reporte de Programas')]),
        ),
    ]
