# Generated by Django 5.1.1 on 2024-10-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporteAcercamientos', '0002_alter_acercamientocooperacion_reporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosquienreporta',
            old_name='correo_electronico',
            new_name='correo_electronico_sesion',
        ),
    ]
