# Generated by Django 5.1.1 on 2024-09-18 18:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAvances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_elaboracion', models.DateField()),
                ('periodo', models.CharField(choices=[('1', 'Periodo 1'), ('2', 'Periodo 2'), ('3', 'Periodo 3')], max_length=1)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('estado', models.IntegerField(choices=[(0, 'Datos Quien Reporta'), (1, 'Datos Cooperante'), (2, 'Logros y Avances')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogrosAvances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_1', models.CharField(default='Automático', max_length=255, verbose_name='Resultado 1')),
                ('logros_avances_1', models.CharField(max_length=50, verbose_name='Logros y/o avances 1')),
                ('departamento_1', models.CharField(max_length=255, verbose_name='Departamento 1')),
                ('municipio_1', models.CharField(max_length=255, verbose_name='Municipio 1')),
                ('adjunto_1', models.FileField(blank=True, null=True, upload_to='adjuntos/', verbose_name='Adjunto 1')),
                ('resultado_2', models.CharField(default='Automático', max_length=255, verbose_name='Resultado 2')),
                ('logros_avances_2', models.CharField(blank=True, max_length=50, verbose_name='Logros y/o avances 2')),
                ('departamento_2', models.CharField(max_length=255, verbose_name='Departamento 2')),
                ('municipio_2', models.CharField(max_length=255, verbose_name='Municipio 2')),
                ('adjunto_2', models.FileField(blank=True, null=True, upload_to='adjuntos/', verbose_name='Adjunto 2')),
                ('resultado_3', models.CharField(default='Automático', max_length=255, verbose_name='Resultado 3')),
                ('logros_avances_3', models.CharField(max_length=50, verbose_name='Logros y/o avances 3')),
                ('departamento_3', models.CharField(max_length=255, verbose_name='Departamento 3')),
                ('municipio_3', models.CharField(max_length=255, verbose_name='Municipio 3')),
                ('adjunto_3', models.FileField(blank=True, null=True, upload_to='adjuntos/', verbose_name='Adjunto 3')),
                ('logros_significativos', models.CharField(max_length=50, verbose_name='Logros significativos en este periodo')),
                ('dificultades', models.CharField(max_length=50, verbose_name='Dificultades presentadas')),
                ('detalle_riesgo', models.CharField(blank=True, help_text="Solo si la respuesta es 'Sí'", max_length=50, null=True, verbose_name='Detalle situación de riesgo')),
                ('observaciones_generales', models.CharField(blank=True, max_length=50, verbose_name='Observaciones o comentarios generales')),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls2.reporteavances')),
            ],
        ),
        migrations.CreateModel(
            name='DatosQuienReporta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('Director de dependencia a nivel nacional', 'Director de dependencia a nivel nacional'), ('Director territorial', 'Director territorial'), ('Enlace de cooperación', 'Enlace de cooperación')], max_length=100)),
                ('dependencia', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('correo_electronico_institucional', models.EmailField(blank=True, max_length=254, null=True)),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls2.reporteavances')),
            ],
        ),
        migrations.CreateModel(
            name='DatosCooperante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cooperante', models.CharField(max_length=255, verbose_name='Nombre del cooperante')),
                ('cual_cooperante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cual (cooperante)')),
                ('identificacion', models.CharField(max_length=50, verbose_name='Identificación')),
                ('nombre_implementador', models.CharField(default='Automático', max_length=255, verbose_name='Nombre del implementador u operador')),
                ('programa_proyecto_plan', models.CharField(max_length=255, verbose_name='Programa/proyecto o plan')),
                ('cual_programa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cual (programa/proyecto o plan)')),
                ('linea_accion', models.CharField(max_length=255, verbose_name='Línea de acción/componente')),
                ('cual_linea_accion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cual (línea de acción)')),
                ('rol_quien_reporta', models.CharField(max_length=255, verbose_name='Rol de quien reporta')),
                ('cual_rol_reporta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cual (rol quien reporta)')),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls2.reporteavances')),
            ],
        ),
        migrations.CreateModel(
            name='ApoyoEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_eventos', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Cantidad de eventos apoyados en el periodo reportado')),
                ('eventos_seleccionados', models.CharField(blank=True, max_length=200)),
                ('otros_eventos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cuales')),
                ('objetivo_principal', models.TextField(max_length=120, verbose_name='Objetivo principal de los eventos apoyados')),
                ('publico_seleccionados', models.CharField(blank=True, max_length=200)),
                ('otros_publicos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cuales')),
                ('cantidad_participantes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Cantidad total de participantes en los eventos en este periodo')),
                ('reporte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls2.reporteavances')),
            ],
        ),
    ]
