# Generated by Django 5.1.1 on 2024-09-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acercamientocooperacion',
            name='realizado',
        ),
        migrations.AlterField(
            model_name='reporteacercamiento',
            name='fecha_elaboracion',
            field=models.DateField(),
        ),
    ]
