# Generated by Django 5.1.1 on 2024-09-18 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reporteacercamiento',
            name='unique_reporteA_per_user_periodo',
        ),
        migrations.AddConstraint(
            model_name='reporteacercamiento',
            constraint=models.UniqueConstraint(fields=('usuario', 'periodo'), name='unique_reporteAcercamiento_per_user_periodo'),
        ),
    ]
