# Generated by Django 5.1.1 on 2024-09-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteacercamiento',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Datos Quien Informa'), (1, 'Acercamiento de Cooperación'), (2, 'Necesidades de Cooperación'), (3, 'Finalizado')], default=0),
        ),
    ]
