# Generated by Django 5.1.1 on 2024-09-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_acercamientocooperacion_realizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acercamientocooperacion',
            name='entidad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='acercamientocooperacion',
            name='temas_perspectivas',
            field=models.TextField(),
        ),
    ]
